#!/usr/bin/env python

from bnirc import *
from os import fork
from re import match
from sys import exit

class App:
	def setOwner(self, host):
		self.ownerHost = host
		self.ownerNick = GrabNick(host)

	def ownerCommands(self, com):
		args = match('([^ ]+)[ ]*(.*)', com)
		args = args.groups()

		if(args[0] == "exec"):
			ParseInput(StringOption("command_char") + args[1] + "\n")
			return 0

		if(args[0] == "say"):
			IrcSay(args[1])
			return 0

		return 1

	def anyoneCommands(self, nick, com, host):
		args = match('([^ ]+)[ ]*(.*)', com)
		args = args.groups()
		DebugMsg("anyoneCommands: " + nick + " " + com)
		DebugMsg(str(args))

		if(args[0] == "owner"):
			IrcMsg(nick, self.ownerNick)
			return 0

		if(args[0] == "testowner"):
			if(self.ownerHost == host):
				IrcMsg(nick, "yes you are my owner")
			else:
				IrcMsg(nick, "no you are not my owner")
			return 0

		return 1

	def onMessage(self, args):
		if(args[2] != CurrentNick()):
			return 1

		if(self.ownerHost == None and args[3] == "testowner"):
			self.setOwner(args[0])
			IrcMsg(self.ownerNick, "You are now my owner")

		if(self.ownerHost == args[0]):
			test = self.ownerCommands(args[3])
			if(test == 0):
				return 0

		nick = GrabNick(args[0])
		return self.anyoneCommands(nick, args[3], args[0])

	def hideMe(self, args=[]):
		SetOption("drop_output", "true")
		SetOption("no_input", "true")
		if(fork() != 0):
			exit(0)

	def __init__(self, nick, channels, server, port = 6667):
		self.ownerHost = None
		self.ownerNick = None
#		SetOption("verbose", "true")
		LoadPlugin("irc_input")
		LoadPlugin("server_strings")
		LoadPlugin("ctcp")
		SetOption("version_string", "bnBot [python + bnIRC goodness]")
		SetOption("default_nick", nick)
		SetOption("log", "on")
		SetOption("realname", "bnBot [maintainer: brandon_niemczyk]")
		SetOption("command_char", "/")
		RegisterServerString("privmsg", 1, 4, self.onMessage)
		# make it silent, and fork
		# comment this out when debugging your script
		self.hideMe()
		IrcConnect(server, 6667)
		ParseInput(StringOption("command_char") + "join " + channels + "\n")
		IrcMain()

selfdestruct_Channels = "#bnirc #justlinux #^D"
inst = App("mrselfdestruct", selfdestruct_Channels, "irc.freenode.net")
