Document: bnirc
Title: Debian bnirc Manual
Author: <insert document author here>
Abstract: This manual describes what bnirc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bnirc/bnirc.sgml.gz

Format: postscript
Files: /usr/share/doc/bnirc/bnirc.ps.gz

Format: text
Files: /usr/share/doc/bnirc/bnirc.text.gz

Format: HTML
Index: /usr/share/doc/bnirc/html/index.html
Files: /usr/share/doc/bnirc/html/*.html


