extern const char FAQ[]; // make sure it gets exported
const char FAQ[] = 
"How come when i join channels they are all in the same window?\n"
"irssi has the annoying habit of opening you a new window everytime you join a channel\n"
"this can be extremely irritating if you chill in 20 rooms that are mostly idle, so in bnirc you have\n"
"to manually switch the window by pressing F{1-12} or with /win {1-12}, if you want to open 3 channels in sep windows\n"
"in your ~/.bnirc do this:\n"
"\n"
"/win 1\n"
"/j #channel1\n"
"/win 2\n"
"/j #some_other_loser_channel\n"
"/win 3\n"
"/j #blar\n"
"\n"
"when i connect, nothing happens!\n"
"you probably didn't 'make install', almost all of bnirc's functionallity is in plugins and it looks for these\n"
"in ${PREFIX}/lib/bnirc/plugins\n"
"moral of the story:  'make install' _then_ run, and if you still have problems, you can bitch at me ;p\n"
"\n"
"does bnirc have DCC capabilities?\n"
"not yet, but it will soon, that is my current project, you can check the status by loading the dcc plugin (/load dcc)\n"
"if it doesn't give you a warning, it's done ;p\n"
"\n"
"how do i load a plugin?\n"
"/load <plugin name>\n"
"\n"
"how do i leave a msg for an idle user\n"
"/queue <nick> your message\n"
"\n"
"how do i save my msgs that i get when i'm gone and check them later?\n"
"/away\n"
"/back\n"
"\n"
"how do i send someone a private message?\n"
"/msg <nick> message\n"
"\n"
"how do i switch channels?\n"
"/join <channel> (if you are already in it, it will just become your \"active\" channel)\n"
"\n"
"how do i use a backup name in my .bnirc?\n"
"just put /nick <backup> before your preferred name, like\n"
"/nick brandon|second\n"
"/nick brandon\n"
"\n"
"where can i get help?\n"
"/connect irc.freenode.net\n"
"/nick lostnewb\n"
"/join #justlinux\n"
"\n"
"when i connect it just keeps reconnecting?\n"
"you probably forgot to /nick after your connect\n"
"\n"
"where can i get a sample .bnirc file\n"
"sample.bnirc should have come with your distribution\n"
"\n"
"how do i change my window in my .bnirc file?\n"
"/win {1-12} or\n"
"/window {1-12}\n"
"\n"
"i read about command <x> for irc, but it doesnt show up in /help !\n"
"only commands that bnirc actually parses locally will show up in help\n"
"if it does not recognize a command, it will blindly pass it to the server\n"
"as is (without the / though of course).  So it should work.\n"
;
